runtime: php
env: flex

runtime_config:
  document_root: public

# Ensure we skip ".env", which is only for local development
skip_files:
  - .env

env_variables:
  # Put production environment variables here.
  APP_LOG: errorlog
  APP_KEY: base64:x3lYSkRpq/krChl7UIsLP4CU9HMtrmr8gCzWjEyZiEk=
  STORAGE_DIR: /tmp
  SESSION_DRIVER: database
  CACHE_DRIVER: database
  ## Set these environment variables according to your CloudSQL configuration.
  DB_HOST: localhost
  DB_DATABASE: CloudKickers
  DB_USERNAME: CloudKickers
  DB_PASSWORD: FIT5120Team03
  DB_SOCKET: "/cloudsql/cloudkickers02-214411:australia-southeast1:cloudkickers"

beta_settings:
    # for Cloud SQL, set this value to the Cloud SQL connection name,
    # e.g. "project:region:cloudsql-instance"
    cloud_sql_instances: "cloudkickers02-214411:australia-southeast1:cloudkickers"
